services:
  reader:
    build: ./reader-service
    container_name: reader_service
    volumes:
      - ./reader-service:/var/www
      - ./data:/var/www/var/imports # For host data folder
      - ./docker/php/conf.d/xdebug_reader.ini:/usr/local/etc/php/conf.d/xdebug_reader.ini
    working_dir: /var/www
    expose:
      - "9000"   # php-fpm listens internally
    networks:
      - microservices

  reader_nginx:
    image: nginx:latest
    container_name: reader_nginx
    volumes:
      - ./reader-service/public:/var/www/public
      - ./docker/nginx/reader.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - reader
    networks:
      - microservices

  writer:
    build: ./writer-service
    container_name: writer_service
    volumes:
      - ./writer-service:/var/www
      - ./docker/php/conf.d/xdebug_writer.ini:/usr/local/etc/php/conf.d/xdebug_writer.ini
    working_dir: /var/www
    expose:
      - "9000"
    networks:
      - microservices

  writer_nginx:
    image: nginx:latest
    container_name: writer_nginx
    volumes:
      - ./writer-service/public:/var/www/public
      - ./docker/nginx/writer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - writer
    networks:
      - microservices

  db:
    image: mysql:8.0
    container_name: writer_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: products_db
    ports:
      - "3307:3306"  # host:container; adjust if 3306 is taken on host
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices

  rabbitmq_broker:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

