# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Http\WriterHttpGateway:
        arguments:
            $baseUrl: '%env(WRITER_BASE_URL)%'

    App\Application\Messaging\PublisherRegistry:
        calls:
            - [add, ['http', '@App\Infrastructure\Messaging\HttpProductImportPublisher']]
            - [ add, [ 'rabbitmq', '@App\Infrastructure\Messaging\RabbitMqProductImportPublisher' ] ]
            # - [add, ['sqs', '@App\Infrastructure\Messaging\SqsProductImportPublisher']]

    App\Infrastructure\Messaging\HttpProductImportPublisher:
        arguments:
            $client: '@http_client'
            $writerBaseUri: '%env(WRITER_BASE_URL)%'

    App\Application\Messaging\ProductImportPublisher:
        alias: App\Application\Messaging\TransportSelectorPublisher

    App\Infrastructure\Messaging\EnvTransportProvider:
        arguments:
            $transportKey: '%env(MESSAGE_TRANSPORT)%'

    App\Application\Messaging\TransportProvider:
        alias: App\Infrastructure\Messaging\EnvTransportProvider

    app.rabbitmq.connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments:
            - '%env(RABBITMQ_HOST)%'
            - '%env(int:RABBITMQ_PORT)%'
            - '%env(RABBITMQ_USER)%'
            - '%env(RABBITMQ_PASSWORD)%'

    App\Infrastructure\Messaging\RabbitMqProductImportPublisher:
        arguments:
            $connection: '@app.rabbitmq.connection'
            $exchangeName: '%env(RABBITMQ_EXCHANGE)%'
            $routingKey: '%env(RABBITMQ_ROUTING_KEY)%'
